Support collection deletion & recreation
cvara/rxdb-hooks pull request #36
Opened 2021-09-02 11:59 UTC by plmercereau

so collection is set again when it is deleted and recreated

2021-09-02 15:41 UTC, cvara commented
Thanks for this @plmercereau.

Could you also add a test case that covers collection deletion + recreation? Something along the lines of this:
https://github.com/cvara/rxdb-hooks/blob/master/tests/useRxData.test.tsx#L735

2021-09-02 17:17 UTC, plmercereau commented
I just pushed a test, but I am not sure it is correct - I'm sorry I am don't really know how to perform tests in React...
The idea is 1. to create a collection - and to use it in the component, 2. to remove it - and to make sure RxData can't find anything and 3. to recreate it and to use the new collection in RxData again.

2021-09-03 12:45 UTC, cvara requested changes

2021-09-03 12:45 UTC, cvara commented on tests/useRxData.test.tsx
> +		});
This is in the right direction. 

Nitpicking really, but to make the test a bit more strict, you could split this into 2 `act()` invocations, one for initially creating the collection and another for deleting/recreating it. Each `act()` could then be followed by 2 assertions: one verifying that the docs of that particular collection are rendered and another verifying that docs of the 'wrong' collection are not.

2021-09-03 12:45 UTC, cvara commented on src/useRxCollection.ts
> +					// sub.unsubscribe();
You can drop the commented line altogether

2021-10-27 10:30 UTC, merged